title: Математический Анализ
description: Конспект лекций по математическому анализу К.П.Кохася 2024-2025
author: Кононов Григорий

baseurl: "/Analysis"
repository: "Yacann/Analysis"

github_username: Yacann
telegram_username: CucumberMayoo

show_excerpts: true

header_pages:
  - _pages/theorems.html
  - _pages/definitions.html

include:
  - _pages

markdown: kramdown
kramdown:
  math_engine: mathjax